### ISSUE TITLE
music sfx

### ISSUE THREAD

**Issue by illume** [pygame/stuntcat#13]
There is music @dirkk0 we can ask to use: http://cloudriver.org/ict/ict.html
And also "Kuba | ThePolish" might be able to contribute music/sfx.

The files should go in:
- suntcat/data/music/
- suntcat/data/sounds

Music for these things.
- intro
- gameover
- game play
- ... (feel free to add music we need or descriptions of the music that would work)

Sfx for these things:
- [x] shark coming in from side of screen... (water, ominous music).
- [x] shark laser fire
- [ ] elephant foot approaches.
- [x] elephant foot stamp.
- [x] wheel rolling.
- [x] jumping cat.
- [x] cat hit by lazer.
- [ ] jumping cat lands.
- [x] eat sound, meow.
- [ ] fish coming in.
- [ ] fish landing on ground.
- [x] crowd/circus noises.
- ... (feel free to add sounds we need or descriptions of the music that would work)

**Comment by illume** [comment]
> stuntcat on a Unicycle with elephant feet falling from the sky. Theme Hybrid.
http://cloudriver.org/ict/ict.html

My opinion:
- 0002 sounds good for a 'tense moment' perhaps GameOver.
- 0013 is kind of 'upbeat' that could work well in the game play section
- I like 0016 for the game play section too.

"hfoxp: 0025 0026 and 0028 might all work well for like loading/intro screens"

**Comment by TjWhale** [comment]
Sfx that would be nice to have:

Elephant foot stomping
Shark firing laser
catching fish / score increase
being hit by not-fish
death / reset
