### ISSUE TITLE
graphics (images)

### ISSUE THREAD

**Issue by illume** [pygame/stuntcat#14]
The images we need.

960x540 is the resolution of our window (half of 1920x1080).

- [x] Elephant feet that stomp down from the top of screen (with long legs made from just a filled/repeated graphic).
- [x] cat on unicycle (perhaps animated along with the cat)
- [x] shark with a lazer in its head
- [ ] background image of a circus tent. There should be a platform at the front which the player rides on top of and some water for the shark in front.
- [ ] small fish the cat has to catch. The fish fly in.

### Cat on Unicycle Animations

For the cat on unicycle, we probably need these frames:
- cat cycling 2-5 frames.
- cat jumping 2-3 frames.
- Note we can flip, rotate inside pygame to do the going left/right animation.

## Sketches.

Some sketches of what the whole scene could look like...

![alt text](https://cdn.discordapp.com/attachments/516882376228601857/518047561286680586/image0.jpg)

![alt text](https://cdn.discordapp.com/attachments/516882376228601857/518047569650122755/unicycle.png)

## Game so far.
![alt text](https://cdn.discordapp.com/attachments/516882376228601857/518031005425205280/unknown.png "our game so far")

**Comment by TjWhale** [comment]
Yeah we need a single static background, of maybe a circus tent? There should be a platform at the front which the player rides on top of and some water for the shark in front maybe?

Also we need a fish sprite and a "not-fish" sprite or set of sprites (so this could be things like circus rings, batons, tomatoes etc just random circus stuff you're meant to judge)

There's also the issue of making the octopus arms animated for the cat / octopus hybrid but that may be more difficult.

**Comment by illume** [comment]
Some sketches of what the whole scene could look like...

![alt text](https://cdn.discordapp.com/attachments/516882376228601857/518047561286680586/image0.jpg)

![alt text](https://cdn.discordapp.com/attachments/516882376228601857/518047569650122755/unicycle.png)

**Comment by illume** [comment]
ps. We have a cat image by @AokiAhishatsu  See data/images/ folder.
