### ISSUE TITLE
cx_freeze to be run on mac, linux, windows

### ISSUE THREAD

**Issue by illume** [pygame/stuntcat#16]
We have CI set up on travis and appveyor.

## Publish to github releases.

- Travis can upload to github on release (via tag). https://docs.travis-ci.com/user/deployment/releases
- Appveyor has built in artifacts (for 6 months). https://www.appveyor.com/docs/deployment/github/

```
python setup.py bdist_dmg
python setup.py bdist_msi
```

Could also do a source release to pypi.

- [ ] desktop shortcuts. Current the game is 'run_game.exe' and there is no shortcut installed. https://stackoverflow.com/questions/15734703/use-cx-freeze-to-create-an-msi-that-adds-a-shortcut-to-the-desktop

**Comment by illume** [comment]
https://github.com/pygame/stuntcat/pull/23

**Comment by AokiAhishatsu** [comment]
Kaabush! https://imgur.com/a/E3fUAIo

**Comment by AokiAhishatsu** [comment]
`pip install stuntcat
python -m stuntcat`
works fine on the same Maschine (but is still old version)

**Comment by illume** [comment]
The msi is still crashing for me on two laptops. It is however with a 64bit build. Maybe that has something to do with it.

**Comment by illume** [comment]
I fixed an issue with cx_freeze and pycparser used by pymunk. Also, I made it produce a 32bit msi for windows.

Still have to put desktop shortcuts and such in.
