### ISSUE TITLE
Game plays too fast

### ISSUE THREAD

**Issue by xandark** [pygame/stuntcat#74]
I love the title of this game and it makes me want to play it, but the fish and the rings move so fast that the game feels pointless to play, like the only way I'll grab any fish is by luck.

**Comment by nachomonkey** [comment]
Agreed. The objects are going way too fast compared to the player. More so than I remember.


Here's a "solution"... :laughing:  Edit `stuntcat/scenes/unisharklazer/__init__.py`, function `_collide_flying_objects`,  line 496 at the moment:

from
`        dt_scaled = self.dt_scaled`

to
`        dt_scaled = self.dt_scaled * 0.15`

This literally puts the flying objects in slow motion (in this case 15% of regular speed, but you could tune it to your liking).

Obviously this isn't the best solution, but it works. A better solution would take a little more work, but anybody motivated enough could fix it.
